function u_one = relaxation_edge(D, delta_t, delta, j, i, u0, u1, vx, vy, c, nx)  
    delta2 = delta*2;
    if i == 1
        u_one = c*(u0(j,i)-delta_t/2*vx(j,i)*(((u0(j,i+1)-u0(j,nx+1))/delta2)+...
            ((u1(j,i+1)-u1(j,nx+1))/delta2)) - delta_t/2*vy(j,i)*(((u0(j+1,i)-u0(j-1,i))/delta2)+...
            ((u1(j+1,i)-u1(j-1,i))/delta2)) + delta_t/2*D*((u0(j,i+1)+u0(j,nx+1)+u0(j+1,i)+u0(j-1,i)-4*u0(j,i))/delta^2+...
            (u1(j,i+1)+u1(j,nx+1)+u1(j+1,i)+u1(j-1,i))/delta^2)); 
    else 
        if i == nx+1
            u_one = c*(u0(j,i)-delta_t/2*vx(j,i)*(((u0(j,1)-u0(j,i-1))/delta2)+...
                ((u1(j,1)-u1(j,i-1))/delta2)) - delta_t/2*vy(j,i)*(((u0(j+1,i)-u0(j-1,i))/delta2)+...
                ((u1(j+1,i)-u1(j-1,i))/delta2)) + delta_t/2*D*((u0(j,1)+u0(j,i-1)+u0(j+1,i)+u0(j-1,i)-4*u0(j,i))/delta^2+...
                (u1(j,1)+u1(j,i-1)+u1(j+1,i)+u1(j-1,i))/delta^2));  
        end
    end
end