function res = is_edge(i,j,nx,ny,i1,j1)
    if (i == 1 && j1 + 1 <= j && j <= ny + 1) || ... 
       (j == ny+1 && 1 <= i && i <= nx + 1) || ... 
       (i == nx+1 && 1 <= j && j <= ny + 1) || ...
       (j == 1 && i1 + 1 <= i && i <= nx + 1) || ...
       (i == i1 + 1 && 1 <= j && j <= j1 + 1) || ...
       (j == j1 + 1 && 1 <= i && i <= i1 + 1)
        res = true;
    else 
        res = false;
    end
end